extends:
  - "@absolunet/eslint-config-node/module"

# Disabled because this is a CommonJS package
rules:
  unicorn/import-index: [error, { ignoreImports: true }]
  unicorn/prefer-module: [off]
  unicorn/prefer-node-protocol: [off]
  import/no-commonjs: [off]
  import/no-import-module-exports: [off]
