# Parser Options
parserOptions:
  ecmaVersion: 2022


# Environments
env:
  node: true


# Rules
rules:

  # Node - Possible Errors
  node/handle-callback-err: [error]
  node/no-new-require: [error]
  node/no-path-concat: [error]
  node/no-unsupported-features/es-builtins: [off]
  node/no-unsupported-features/es-syntax: [off]

  # Node - Stylistic Issues
  node/callback-return: [error]
  node/exports-style: [error, 'module.exports']
  node/global-require: [error]
  node/no-mixed-requires: [error]
  node/no-process-env: [error]
  node/prefer-global/buffer: [error, never]
  node/prefer-global/console: [error, always]
  node/prefer-global/process: [error, always]
  node/prefer-global/text-decoder: [error, never]
  node/prefer-global/text-encoder: [error, never]
  node/prefer-global/url-search-params: [error, never]
  node/prefer-global/url: [error, never]
  node/prefer-promises/dns: [error]
  node/prefer-promises/fs: [error]
