extends: '@absolunet/browser'


# Environments
env:
  jquery: true


# Globals
globals:
  global: readonly

  # nwayo
  konstan: readonly
  app: readonly
  __: readonly
  toolbox: readonly
  PROJECT: readonly
  DOM_PARSED: readonly
  DOCUMENT_LOADED: readonly
  GLOBAL_JQUERY_LOADED: readonly

  # nwayo vendors
  _: readonly
  Modernizr: readonly
  pinki: readonly

  # Classic libs
  addthis: readonly
  addthis_config: writable
  addthis_share: writable
  Cookies: readonly
  FastClick: readonly
  Foundation: readonly
  google: readonly
  kafe: readonly
  WebFont: readonly
  whatInput: readonly


# Rules
rules:

  # Possible Errors
  no-console: [warn]
  no-debugger: [warn]


  # Best Practices
  no-alert: [warn]
  no-warning-comments: [warn, { location: anywhere }]


  # 🦄 Unicorn
  unicorn/consistent-function-scoping: [off]
  unicorn/no-unreadable-iife: [off]
