plugins:
  - 'package-json' # (from @magento/eslint-config)

extends:
  - 'eslint:recommended'               # (from @magento/eslint-config)
  - 'plugin:jsx-a11y/recommended'      # (from @magento/eslint-config)
  - 'plugin:package-json/recommended'  # (from @magento/eslint-config)
  - '@absolunet/react'


globals:
  process: readonly
  module: readonly
  googleMapsLoaded: readonly
  STORE_NAME: readonly
  STORE_CONFIGS: readonly
  AVAILABLE_STORE_VIEWS: readonly
  STORE_VIEW_LOCALE: readonly
  STORE_VIEW_CODE: readonly
  _ltk: readonly


rules:

  # Variables
  no-undef: [off]
  no-restricted-globals:
    - error
    - name: 'window'
      message: ''


  # Stylistic Issues
  camelcase: [off]  # Not compatible with Magento naming convention
  padded-blocks: [off] # Made the code look less structured


  # Best Practices
  no-prototype-builtins: [off]
  no-useless-escape: [off]
  no-warning-comments: [warn, { location: anywhere }]
  no-restricted-imports:
    - error
    - paths:
        - name: '@magento/venia-ui/lib/classify'
          importNames: [ 'mergeClasses' ]
          message: 'Please import "useStyle" instead.'


  # 🦄 Unicorn
  unicorn/prevent-abbreviations:
    - error
    - checkProperties: true
      checkFilenames: false
      replacements:
        props: false
        params: false
      allowList:
        propClasses: true
        useParams: true
        ref: true
  unicorn/no-keyword-prefix: [off]
  unicorn/template-indent:
    - error
    - indent: 4


  # React - JSX-specific rules
  react/jsx-no-literals:
    - error
    - allowedStrings: []
      ignoreProps: true # Use ignoreProps: false to catch label/title/alt text, etc. Has the downside of erroring on "id" and other string props.
      noStrings: true

  react/jsx-one-expression-per-line: [off]
  react/jsx-props-no-spreading: [off]
  react/function-component-definition:
    - error
    - namedComponents: 'arrow-function'
      unnamedComponents: 'arrow-function'
  react/jsx-indent:
    - error
    - 4
  react/jsx-indent-props:
    - error
    - 4
  react/prop-types:
    - error
    - ignore: ['children']


  # React Hooks
  react-hooks/exhaustive-deps: [warn]  # Until we decide on a strategy for refactoring useEffect with an empty array


  # Import
  # import/prefer-default-export: [off]



overrides:
  - files: ['*.spec.js']
    env:
      jest: true

  - files: ['*.wrap.*']
    rules:
      func-names: [off]

  - files: ['use*.js']
    excludedFiles: ['*.spec.js', '*.wrap.js', '*.targetables.js', '*.gql.*']
    rules:
      import/prefer-default-export: [off]
      import/no-default-export: [off]
